/**
 * @fileoverview gRPC-Web generated client stub for echo
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: echo.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as echo_pb from './echo_pb';


export class EchoClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorEchoStream = new grpcWeb.MethodDescriptor(
    '/echo.Echo/EchoStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    echo_pb.Empty,
    echo_pb.EchoResponse,
    (request: echo_pb.Empty) => {
      return request.serializeBinary();
    },
    echo_pb.EchoResponse.deserializeBinary
  );

  echoStream(
    request: echo_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<echo_pb.EchoResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/echo.Echo/EchoStream',
      request,
      metadata || {},
      this.methodDescriptorEchoStream);
  }

  methodDescriptorEchoRequest = new grpcWeb.MethodDescriptor(
    '/echo.Echo/EchoRequest',
    grpcWeb.MethodType.UNARY,
    echo_pb.Empty,
    echo_pb.EchoResponse,
    (request: echo_pb.Empty) => {
      return request.serializeBinary();
    },
    echo_pb.EchoResponse.deserializeBinary
  );

  echoRequest(
    request: echo_pb.Empty,
    metadata: grpcWeb.Metadata | null): Promise<echo_pb.EchoResponse>;

  echoRequest(
    request: echo_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: echo_pb.EchoResponse) => void): grpcWeb.ClientReadableStream<echo_pb.EchoResponse>;

  echoRequest(
    request: echo_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: echo_pb.EchoResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/echo.Echo/EchoRequest',
        request,
        metadata || {},
        this.methodDescriptorEchoRequest,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/echo.Echo/EchoRequest',
    request,
    metadata || {},
    this.methodDescriptorEchoRequest);
  }

}

